import {
  MODE_CITY,
  PHASE_SPAWN_DELAY,
  RESULT_NONE,
  TIER_NONE,
  TYPE_RESIDENTIAL,
} from '../../src/types';
import type { SimState } from '../../src/types';

/** Test-only builder for a minimal, valid `SimState`, for unit tests of individual modules. */
export function makeState(overrides: Partial<SimState> = {}): SimState {
  return {
    typeCode: TYPE_RESIDENTIAL,
    modeCode: MODE_CITY,
    assist: 0,
    seed: 1,
    tick: 0,
    rngState: 1,
    phase: PHASE_SPAWN_DELAY,
    phaseTimer: 0,
    result: RESULT_NONE,
    finalScore: 0,
    strikes: 0,
    score: 0,
    floors: 0,
    restX: [0],
    leanSum: 0,
    lean: 0,
    isRoof: 0,
    roofCommitted: 0,
    craneCenterX: 0,
    cranePhase: 0,
    craneIncrement: 0,
    craneSpeed: 1000,
    craneX: 0,
    releaseX: 0,
    releaseTick: 0,
    landingTick: 0,
    combo: 0,
    comboMult: 1000,
    goodCount: 0,
    sensitivity: 1000,
    stabilizer: 1000,
    swayPhase: 0,
    swayIncrement: 0,
    swayAmp: 0,
    swayTarget: 0,
    swayS: 0,
    pendingInput: 0,
    lastOffset: 0,
    lastTier: TIER_NONE,
    ...overrides,
  };
}
